#!/usr/bin/with-contenv sh

# Environment variables
export PGSQL_HOST 
export POSTFIX_PGSQL_USER
export POSTFIX_PGSQL_PASS
export POSTFIX_PGSQL_DB

export SPAMASSASSIN_HOST

export ADMIN_EMAIL
export SMTP_HOSTNAME 
export SMTP_DOMAIN
export DOVECOT_HOST

export SKIP_DB_SETUP
export SKIP_DOVECOT_SETUP

#mkdir -p /private/ssl/

if [[ -f /private/vars.sh ]]; then
    source /private/vars.sh
fi

SKIP_DOVECOT_SETUP=${SKIP_DOVECOT_SETUP:-}

if [[ -z $SKIP_DOVECOT_SETUP ]]; then
    echo "copying config files from /opt/dovecot.default/ to /etc/dovecot/"
    cp -r /opt/dovecot.default/* /etc/dovecot/
    echo "running sieve script"
    sievec /etc/dovecot/sieve-spam.sieve

    echo "checking parameters"
    ADMIN_EMAIL=${ADMIN_EMAIL}
    if [[ -z ${ADMIN_EMAIL} ]]; then
        echo "WARN: ADMIN_EMAIL not found. using default"
        ADMIN_EMAIL="admin@domain.com"
    fi
    echo "ADMIN_EMAIL set to $ADMIN_EMAIL"

    SMTP_DOMAIN=${SMTP_DOMAIN}
    if [[ -z ${SMTP_DOMAIN} ]]; then
        echo "WARN: SMTP_DOMAIN not found. using default"
        SMTP_DOMAIN=$(echo $ADMIN_EMAIL | sed 's/.*@//')
    fi
    echo "SMTP_DOMAIN set to $SMTP_DOMAIN"

    DOVECOT_HOST=${DOVECOT_HOST:-}
    if [[ -z ${DOVECOT_HOST} ]]; then
      echo "WARN: DOVECOT_HOST not found. using default"
      DOVECOT_HOST=dovecot.$(echo $ADMIN_EMAIL | sed 's/.*@//')
    fi
    echo "DOVECOT_HOST set to $DOVECOT_HOST"

    PGSQL_HOST=${PGSQL_HOST:-}
    if [[ -z ${PGSQL_HOST} ]]; then
        echo "WARN: PGSQL_HOST not found. using default"
        PGSQL_HOST=pgsql.$(echo $ADMIN_EMAIL | sed 's/.*@//')
    fi
    echo "PGSQL_HOST set to $PGSQL_HOST"

    POSTFIX_PGSQL_USER=${POSTFIX_PGSQL_USER:-}
    if [[ -z ${POSTFIX_PGSQL_USER} ]]; then
        echo "WARN: POSTFIX_PGSQL_USER not found. using default"
        POSTFIX_PGSQL_USER=user
    fi
    echo "POSTFIX_PGSQL_USER set to $POSTFIX_PGSQL_USER"

    POSTFIX_PGSQL_PASS=${POSTFIX_PGSQL_PASS:-}
    if [[ -z ${POSTFIX_PGSQL_PASS} ]]; then
        echo "WARN: POSTFIX_PGSQL_PASS not found. using default"
        POSTFIX_PGSQL_PASS=password
    fi
    echo "POSTFIX_PGSQL_PASS set"

    POSTFIX_PGSQL_DB=${POSTFIX_PGSQL_DB:-}
    if [[ -z ${POSTFIX_PGSQL_DB} ]]; then
        echo "WARN: POSTFIX_PGSQL_DB not found. using default"
        POSTFIX_PGSQL_DB=db
    fi
    echo "POSTFIX_PGSQL_DB set to $POSTFIX_PGSQL_DB"

    echo "replacing placeholders in /etc/dovecot/conf.d/10-auth.conf"
    sed -i "s/#*\(\!include auth-system.conf.ext\)/#\1/"  /etc/dovecot/conf.d/10-auth.conf
    sed -i "s/#\(\!include auth-sql.conf.ext\)/\1/"  /etc/dovecot/conf.d/10-auth.conf
    echo "replacing placeholders in /etc/dovecot/dovecot-sql.conf.ext"
    sed -i "s/##PGSQL_HOST##/$PGSQL_HOST/g" /etc/dovecot/dovecot-sql.conf.ext
    sed -i "s/##POSTFIX_PGSQL_USER##/$POSTFIX_PGSQL_USER/g" /etc/dovecot/dovecot-sql.conf.ext
    sed -i "s/##POSTFIX_PGSQL_PASS##/$POSTFIX_PGSQL_PASS/g" /etc/dovecot/dovecot-sql.conf.ext
    sed -i "s/##POSTFIX_PGSQL_DB##/$POSTFIX_PGSQL_DB/g" /etc/dovecot/dovecot-sql.conf.ext
    echo "chmoding /etc/dovecot/dovecot-sql.conf.ext to 0600"
    chmod 0600 /etc/dovecot/dovecot-sql.conf.ext
    echo "replacing placeholders in /etc/dovecot/dovecot-sql.conf"
    sed -i "s/##PGSQL_HOST##/$PGSQL_HOST/g" /etc/dovecot/dovecot-sql.conf
    sed -i "s/##POSTFIX_PGSQL_USER##/$POSTFIX_PGSQL_USER/g" /etc/dovecot/dovecot-sql.conf
    sed -i "s/##POSTFIX_PGSQL_PASS##/$POSTFIX_PGSQL_PASS/g" /etc/dovecot/dovecot-sql.conf
    sed -i "s/##POSTFIX_PGSQL_DB##/$POSTFIX_PGSQL_DB/g" /etc/dovecot/dovecot-sql.conf
    echo "replacing placeholders in /etc/dovecot/conf.d/15-lda.conf"
    sed -i "s/##ADMIN_EMAIL##/$ADMIN_EMAIL/g" /etc/dovecot/conf.d/15-lda.conf
    sed -i "s/##SMTP_HOSTNAME##/$SMTP_HOSTNAME/g" /etc/dovecot/conf.d/15-lda.conf
    sed -i "s/##POSTFIX_HOST##/$POSTFIX_HOST/g" /etc/dovecot/conf.d/15-lda.conf

    echo "configuration done"
    echo

#    chown -R mail:dovecot /etc/dovecot
#    chmod -R o-rwx /etc/dovecot

fi

mkdir -p /srv/mail/mailboxes
mkdir -p /srv/mail/sieve

#chown -R mail:mail /srv/mail/*

echo "generating SSL certificate"
mkdir -p /private/ssl
if [[ ! -f /private/ssl/ssl_certificate.pem ]]; then
    DOMAIN=$(echo $ADMIN_EMAIL | sed 's/.*@//')
    openssl req -new -newkey rsa:2048 -days 30 -nodes -x509 \
    -keyout /private/ssl/ssl_private_key.pem \
    -out /private/ssl/ssl_certificate.pem \
    -subj '/O=Company/OU=Department/CN=www.'$DOMAIN
fi
