#!/usr/bin/with-contenv sh

#echo "Running FreshClam to update definitions..."
#s6-setuidgid clamav freshclam --verbose --stdout 2>&1

#echo "Starting FreshClam daemon..."
#s6-setuidgid clamav freshclam --verbose --stdout --daemon 2>&1
#exec freshclam --verbose --stdout --daemon 2>&1
